name: CI - Linux - ROS

on:
  push:
    branches:
    - master
    - devel
  pull_request:
    branches:
    - master
    - devel

jobs:
  ROS:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, BUILDER: catkin_tools}
          - {ROS_DISTRO: rolling}
          - {ROS_DISTRO: jazzy}
          - {ROS_DISTRO: iron}
          - {ROS_DISTRO: humble}
    env:
      CCACHE_DIR: /github/home/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}
      - uses: 'ros-industrial/industrial_ci@eb3ea328ff056aa2435d5b3493e7e2929c310f8e'
        env: ${{ matrix.env }}
